[package]
name = "heroku-rust-hello"
version = "0.1.0"
authors = ["ThePFMind <thepfmind@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0.8"